server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lllZLXlll/SpringCloudConfig/
          search-paths: test-config
          username:
          password:


      label: master
