server:
  port: 8766

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes: # 配置路由
    api-a:
      path: /api-a/** # 路径
      service-id: service-ribbon # 对应路径调用的服务

    api-b:
      path: /api-b/**
      service-id: service-feign
